# This playbook should only contain general customization required to deploy a
# K8S cluster ready to run GCS. Any specific customizations with respect to the
# vagrant environment needs to be done in vagrant-playbook.
---
- name: Deploy K8S
  import_playbook: "kubespray/cluster.yml"
  vars:
    dns_mode: "coredns"
    docker_mount_flags: "shared"
    kube_network_plugin: "flannel"
    kube_version: "v1.13.1"
    local_volumes_enabled: true
    kube_feature_gates: ["VolumeSnapshotDataSource=true"]

- name: Fetch config
  hosts: kube-master[0]
  become: true
  tasks:
    - name: Retrieve kubectl config
      fetch:
        dest: ./kubeconfig
        flat: yes
        src: /root/.kube/config

- name: Copy kube config for vagrant user
  hosts: kube-master
  remote_user: vagrant
  tasks:
    - name: Create a directory
      file:
         path: /home/vagrant/.kube
         state: directory
         group: vagrant
         owner: vagrant
         mode: 755

    - name: Copy kube config for vagrant user
      copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
